const queryKeys = {
    clusters: "clusters",
    slots: "slots",
    buckets: "buckets",
    cluster: "cluster",
    checkAccess: "checkAccess",
    stores: "stores",
    vendors: "vendors",
    vendor: "vendor",
    resources: "resources",
    actions: "actions",
    departments: "departments",
    department: "department",
    recordTypes: "recordTypes",
    recordType: "recordType",
    roles: "roles",
    role: "role",
    users: "user",
    user: "user",
    servers: "servers",
    server: "server",
    serverAddress: "serverAddress",
    serverTypes: "serverTypes",
    settingTrafficReport: "settingTrafficReport",
    settingBalanceReport: "settingBalanceReport",
    settingsBalancing: "settingsBalancing",
    settingBalancing: "settingBalancing",
    settingsKey: "settingsKey",
    settingKey: "settingKey",
    settingsSynch: "settingsSynch",
    settingSynch: "settingSynch",
    settingsTraffic: "settingsTraffic",
    settingTraffic: "settingTraffic",
    token: "token",
    redisDebug: "redisDebug",
    clickHouseDebug: "clickHouseDebug",
    cloneSessions: "cloneSessions",
    cloneSession: "cloneSession",
    audit: "audit",
};

export default queryKeys;
